spring:
  application:
    name: admin-security-server
  security: # 配置登录用户名和密码，在界面上登录的时候要用
    user:
      name: lijie
      password: 123456
  boot:  # 不显示admin-security-server的监控信息（也就是不监控自己的信息）
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 9301
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/ #注册进eureka

